export const demoData = [
    {
        id: 'e101',
        createdAt: 1551133930500,
        subject: 'Miss you!',
        body: 'Would love to catch up sometimes',
        isRead: false,
        isStared: false,
        sentAt: 1554133930594,
        removedAt: null,
        from: 'momo@momo.com',
        to: 'user@appsus.com',
    },
    {
        id: 'e102',
        createdAt: 1551133930501,
        subject: 'Make pasta!',
        body: 'Would you like to make pasta?',
        isRead: false,
        isStared: false,
        sentAt: 1531183930594,
        removedAt: null,
        from: 'pomo@pomo.com',
        to: 'user@appsus.com',
    },
    {
        id: 'e103',
        createdAt: 1551133930501,
        subject: 'Cook dinner!',
        body: 'Would you like to make pasta?',
        isRead: false,
        isStared: false,
        sentAt: 1531233930594,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'pomo@pomo.com',
    },
    {
        id: 'e104',
        createdAt: 1551133930501,
        subject: 'Home coming',
        body: 'Would you like to make pasta?',
        isRead: false,
        isStared: false,
        sentAt: 1531133730594,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'pomo@pomo.com',
    },
    {
        id: 'e201',
        createdAt: 1705802400000,       // 21 Jan 2024
        subject: 'Weekend trip details',
        body: 'Here’s the Airbnb link and our packing list – let me know!',
        isRead: true,
        isStarred: false,
        sentAt: 1705802700000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'liam@wanderlust.co'
    },
    {
        id: 'e202',
        createdAt: 1706364000000,       // 27 Jan 2024
        subject: 'Conference slides attached',
        body: 'FYI – final deck is attached in PDF. See you in Berlin.',
        isRead: true,
        isStarred: false,
        sentAt: 1706364300000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'team@devsummit.org'
    },
    {
        id: 'e203',
        createdAt: 1706536800000,
        subject: 'Friday dinner reservation',
        body: 'Table for 4 at 19:30 confirmed – see you at Trattoria Verde.',
        isRead: false,
        isStarred: false,
        sentAt: 1706537100000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'maria@verde.it'
    },
    {
        id: 'e204',
        createdAt: 1706796000000,
        subject: 'Invoice #1047 – January services',
        body: 'Hi Alex, invoice attached. Net-30 as usual – thanks!',
        isRead: true,
        isStarred: true,
        sentAt: 1706796300000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'billing@pixelcraft.io'
    },
    {
        id: 'e205',
        createdAt: 1707138000000,
        subject: 'Happy birthday! 🎉',
        body: 'Hope the cupcakes reached you in time. Have a great one!',
        isRead: false,
        isStarred: false,
        sentAt: 1707138300000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'sophie@cakesandco.uk'
    },
    {
        id: 'e206',
        createdAt: 1707570000000,
        subject: 'Gym membership freeze',
        body: 'Please pause my membership from 1 Feb – travelling for work.',
        isRead: true,
        isStarred: false,
        sentAt: 1707570300000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'support@fitcore.com'
    },
    {
        id: 'e207',
        createdAt: 1707742800000,
        subject: 'GitHub access request',
        body: 'Could you add me to the “infra-prod” repo? Need to push a fix.',
        isRead: false,
        isStarred: false,
        sentAt: 1707743100000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'ops@cloudninja.dev'
    },
    {
        id: 'e208',
        createdAt: 1707915600000,
        subject: 'Spotify playlist for road trip',
        body: 'Curated 3h of 90’s classics – link below. Add anything!',
        isRead: true,
        isStarred: false,
        sentAt: 1707915900000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'hannah@mixmaster.fm'
    },
    {
        id: 'e209',
        createdAt: 1708261200000,
        subject: 'Quarterly OKRs draft',
        body: 'Take a look and comment before our Monday sync?',
        isRead: true,
        isStarred: true,
        sentAt: 1708261500000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'leadership@acme.com'
    },
    {
        id: 'e210',
        createdAt: 1708520400000,
        subject: 'Passport renewal form',
        body: 'Filled my part. Please sign section 2 and return. Thanks!',
        isRead: false,
        isStarred: false,
        sentAt: 1708520700000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'linda@state.gov'
    },
    {
        id: 'e211',
        createdAt: 1708783200000,
        subject: 'Dog-sitting this weekend?',
        body: 'Rex would love company – can you drop by Sat & Sun?',
        isRead: true,
        isStarred: false,
        sentAt: 1708783500000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'ben@petpals.org'
    },
    {
        id: 'e212',
        createdAt: 1709042400000,
        subject: 'Recipe swap – shakshuka',
        body: 'Tried your chilli – here’s my recipe in return 😊',
        isRead: false,
        isStarred: true,
        sentAt: 1709042700000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'chef@spicyroutes.com'
    },
    {
        id: 'e213',
        createdAt: 1709301600000,
        subject: 'Meeting notes – Feb Board',
        body: 'Attached minutes & action items. Let me know if anything’s off.',
        isRead: true,
        isStarred: false,
        sentAt: 1709301900000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'board@stellar-fund.io'
    },
    {
        id: 'e214',
        createdAt: 1709474400000,
        subject: 'Photo proofs from shoot',
        body: 'Raw JPEGs in Drive. Choose favorites for editing.',
        isRead: false,
        isStarred: false,
        sentAt: 1709474700000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'studio@flashflash.pro'
    },
    {
        id: 'e215',
        createdAt: 1709733600000,
        subject: 'Carpool tomorrow?',
        body: 'Leaving at 08:00 sharp – seat is yours if you need it.',
        isRead: true,
        isStarred: false,
        sentAt: 1709733900000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'yara@greenride.app'
    },
    {
        id: 'e216',
        createdAt: 1709992800000,
        subject: 'New logo concept V3',
        body: 'Latest SVG attached – feedback welcomed by Friday.',
        isRead: false,
        isStarred: false,
        sentAt: 1709993100000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'design@pixelpush.studio'
    },
    {
        id: 'e217',
        createdAt: 1710165600000,
        subject: 'Ski trip waiver',
        body: 'Signed PDF attached – please confirm receipt.',
        isRead: false,
        isStarred: false,
        sentAt: 1710165900000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'club@alpine-ventures.eu'
    },
    {
        id: 'e218',
        createdAt: 1710338400000,
        subject: 'Newsletter March draft',
        body: 'Added analytics section – thoughts?',
        isRead: true,
        isStarred: true,
        sentAt: 1710338700000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'editor@insight-weekly.com'
    },
    {
        id: 'e219',
        createdAt: 1710597600000,
        subject: 'Laptop warranty claim',
        body: 'Serial # and issue description enclosed. Awaiting RMA.',
        isRead: true,
        isStarred: false,
        sentAt: 1710597900000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'support@technest.io'
    },
    {
        id: 'e220',
        createdAt: 1710856800000,
        subject: 'Friday demo link',
        body: 'Zoom ID: 891-445-221 at 14:00 UTC. Passcode: demo',
        isRead: false,
        isStarred: false,
        sentAt: 1710857100000,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'demo-team@vividware.com'
    },

    {
        id: 'e221',
        createdAt: 1705759200000,
        subject: 'Your order has shipped 🚚',
        body: 'Track your package #A73 here: https://ship.track/1a2b',
        isRead: false,
        isStarred: false,
        sentAt: 1705759500000,
        removedAt: null,
        from: 'sales@printsupply.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e222',
        createdAt: 1706277600000,
        subject: 'Password reset request',
        body: 'Click this link to reset your Securify account (expires in 10 min).',
        isRead: true,
        isStarred: false,
        sentAt: 1706277810000,
        removedAt: null,
        from: 'no-reply@securify.net',
        to: 'user@appsus.com'
    },
    {
        id: 'e223',
        createdAt: 1706443200000,
        subject: '🎫 Concert Tickets – Order #4589',
        body: 'Attached are your PDF tickets. Doors open 19:00.',
        isRead: true,
        isStarred: true,
        sentAt: 1706443500000,
        removedAt: null,
        from: 'tickets@eventi.io',
        to: 'user@appsus.com'
    },
    {
        id: 'e224',
        createdAt: 1706698800000,
        subject: 'Monthly credit card statement',
        body: 'Your January statement is ready in the portal.',
        isRead: false,
        isStarred: false,
        sentAt: 1706699100000,
        removedAt: null,
        from: 'alerts@bank-plus.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e225',
        createdAt: 1706958000000,
        subject: 'Comment on your blog post',
        body: 'Loved your React article – left a few questions in the comments.',
        isRead: true,
        isStarred: false,
        sentAt: 1706958300000,
        removedAt: null,
        from: 'devon@codechat.dev',
        to: 'user@appsus.com'
    },
    {
        id: 'e226',
        createdAt: 1707217200000,
        subject: 'Figma file access granted',
        body: 'You now have edit rights to “New Landing Page”.',
        isRead: false,
        isStarred: false,
        sentAt: 1707217500000,
        removedAt: null,
        from: 'figma-bot@figma.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e227',
        createdAt: 1707480000000,
        subject: 'Welcome to Beta Program',
        body: 'Here’s your invite code for NovaOS beta.',
        isRead: true,
        isStarred: false,
        sentAt: 1707480300000,
        removedAt: null,
        from: 'beta@novaos.ai',
        to: 'user@appsus.com'
    },
    {
        id: 'e228',
        createdAt: 1707742800000,
        subject: 'Your package is delayed',
        body: 'Apologies – weather has affected delivery ETA. New date: 5 Feb.',
        isRead: false,
        isStarred: false,
        sentAt: 1707743100000,
        removedAt: null,
        from: 'support@courierking.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e229',
        createdAt: 1708002000000,
        subject: 'Slack verification code',
        body: 'Use 482-613 to finish signing in. This code expires in 10 min.',
        isRead: true,
        isStarred: false,
        sentAt: 1708002300000,
        removedAt: null,
        from: 'no-reply@slack.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e230',
        createdAt: 1708261200000,
        subject: 'New comment on PR #92',
        body: '“LGTM – just one nitpick about the docs.”',
        isRead: true,
        isStarred: true,
        sentAt: 1708261500000,
        removedAt: null,
        from: 'github@notifications.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e231',
        createdAt: 1708520400000,
        subject: 'Weekly digest: Data Science Today',
        body: 'Top 5 stories you might’ve missed – read online.',
        isRead: false,
        isStarred: false,
        sentAt: 1708520700000,
        removedAt: null,
        from: 'digest@dstoday.org',
        to: 'user@appsus.com'
    },
    {
        id: 'e232',
        createdAt: 1708693200000,
        subject: 'Receipt – Coffee Subscription',
        body: 'Thank you for your payment of $23.00 (Feb cycle).',
        isRead: true,
        isStarred: false,
        sentAt: 1708693500000,
        removedAt: null,
        from: 'orders@beanbox.cafe',
        to: 'user@appsus.com'
    },
    {
        id: 'e233',
        createdAt: 1708952400000,
        subject: 'Spotify: new follower alert',
        body: 'Aria Blake just followed your playlist “Deep Focus”.',
        isRead: false,
        isStarred: false,
        sentAt: 1708952700000,
        removedAt: null,
        from: 'no-reply@spotify.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e234',
        createdAt: 1709211600000,
        subject: 'Flight check-in now open',
        body: 'Seat 14A is pre-selected. Check-in closes 02:30 UTC.',
        isRead: true,
        isStarred: false,
        sentAt: 1709211900000,
        removedAt: null,
        from: 'alerts@skyways.air',
        to: 'user@appsus.com'
    },
    {
        id: 'e235',
        createdAt: 1709470800000,
        subject: '[Reminder] Dentist appointment',
        body: 'Friendly reminder: 12 Feb at 15:00 with Dr. Cohen.',
        isRead: false,
        isStarred: true,
        sentAt: 1709471100000,
        removedAt: null,
        from: 'office@smilesclinic.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e236',
        createdAt: 1709733600000,
        subject: 'Your February horoscope',
        body: 'Pisces season brings new connections and bold ideas.',
        isRead: true,
        isStarred: false,
        sentAt: 1709733900000,
        removedAt: null,
        from: 'stars@astrolite.app',
        to: 'user@appsus.com'
    },
    {
        id: 'e237',
        createdAt: 1709992800000,
        subject: 'Zoom recording ready',
        body: 'Download link (expires in 7 days): https://zoom.us/rec/xyz',
        isRead: false,
        isStarred: false,
        sentAt: 1709993100000,
        removedAt: null,
        from: 'no-reply@zoom.us',
        to: 'user@appsus.com'
    },
    {
        id: 'e238',
        createdAt: 1710165600000,
        subject: 'MacOS update 14.3 available',
        body: 'Restart tonight to install the latest security fixes.',
        isRead: false,
        isStarred: false,
        sentAt: 1710165900000,
        removedAt: null,
        from: 'update@apple.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e239',
        createdAt: 1710424800000,
        subject: 'LinkedIn job alert – 3 new roles',
        body: 'Data Engineer, Backend Developer, DevOps Specialist',
        isRead: true,
        isStarred: false,
        sentAt: 1710425100000,
        removedAt: null,
        from: 'jobs@linkedin.com',
        to: 'user@appsus.com'
    },
    {
        id: 'e240',
        createdAt: 1710684000000,
        subject: 'Printer low on toner',
        body: 'Office printer #2 is at 5 % – replace soon.',
        isRead: false,
        isStarred: false,
        sentAt: 1710684300000,
        removedAt: null,
        from: 'iot@print-sentinel.io',
        to: 'user@appsus.com'
    }


]