export const demoData = [
    {
        id: 'e101',
        createdAt: 1551133930500,
        subject: 'Miss you!',
        body: 'Would love to catch up sometimes',
        isRead: false,
        isStared: false,
        sentAt: 1554133930594,
        removedAt: null,
        from: 'momo@momo.com',
        to: 'user@appsus.com',
    },
    {
        id: 'e102',
        createdAt: 1551133930501,
        subject: 'Make pasta!',
        body: 'Would you like to make pasta?',
        isRead: false,
        isStared: false,
        sentAt: 1531183930594,
        removedAt: null,
        from: 'pomo@pomo.com',
        to: 'user@appsus.com',
    },
    {
        id: 'e103',
        createdAt: 1551133930501,
        subject: 'Cook dinner!',
        body: 'Would you like to make pasta?',
        isRead: false,
        isStared: false,
        sentAt: 1531233930594,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'pomo@pomo.com',
    },
    {
        id: 'e104',
        createdAt: 1551133930501,
        subject: 'Home coming',
        body: 'Would you like to make pasta?',
        isRead: false,
        isStared: false,
        sentAt: 1531133730594,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'pomo@pomo.com',
    }
]